POST http://localhost:5050/disciplina
Content-Type: application/json

{
    "nome": "Geografia",
    "descricao": "Estudo da terra"
}

###

GET http://localhost:5050/disciplina/

###

GET http://localhost:5050/disciplina/2

###

PUT http://localhost:5050/disciplina/disable/2
Content-Type: application/json

###

GET http://localhost:5050/disciplina/enabled
