### Retorna todos alunoHasTurma
GET http://localhost:5050/alunoHasTurma

### Retorna alunoHasTurma por idAluno e idTurma
POST http://localhost:5050/alunoHasTurma
Content-Type: application/json

{
    "idAluno": 1,
    "idTurma": 1
}

### Retorna someente ativos
GET http://localhost:5050/alunoHasTurma/actives

### Cria alunoHasTurma 1
POST http://localhost:5050/alunoHasTurma/create
Content-Type: application/json

{
    "idAluno": 1,
    "idTurma": 1
}

### Cria alunoHasTurma 2
POST http://localhost:5050/alunoHasTurma/create
Content-Type: application/json

{
    "idAluno": 2,
    "idTurma": 2
}

### Cria alunoHasTurma 3
POST http://localhost:5050/alunoHasTurma/create
Content-Type: application/json

{
    "idAluno": 3,
    "idTurma": 3
}

### Inativa alunoHasTurma
PUT http://localhost:5050/alunoHasTurma/disable/
Content-Type: application/json

{
    "idAluno": 2,
    "idTurma": 2
}

### Ativa alunoHasTurma
PUT http://localhost:5050/alunoHasTurma/activate/
Content-Type: application/json

{
    "idAluno": 2,
    "idTurma": 2
}
