### Retorna todas as disciplinas
GET http://localhost:5050/disciplina

### Retorna somente ativas
GET http://localhost:5050/disciplina/actives

### Retorna disciplina por id
GET http://localhost:5050/disciplina/1

### Cria disciplina 1
POST http://localhost:5050/disciplina/create
Content-Type: application/json

{
    "nome": "Disciplina 1",
    "codigo": "DISC1",
    "periodo": 1,
    "descricao": "Descrição 1"
}

### Cria disciplina 2
POST http://localhost:5050/disciplina/create
Content-Type: application/json

{
    "nome": "Disciplina 2",
    "codigo": "DISC2",
    "periodo": 2,
    "descricao": "Descrição 2"
}

### Cria disciplina 3
POST http://localhost:5050/disciplina/create
Content-Type: application/json

{
    "nome": "Disciplina 3",
    "codigo": "DISC3",
    "periodo": 3,
    "descricao": "Descrição 3"
}

### Cria disciplina 4
POST http://localhost:5050/disciplina/create
Content-Type: application/json

{
    "nome": "Disciplina 4",
    "codigo": "DISC4",
    "periodo": 4,
    "descricao": "Descrição 4"
}

### Cria disciplina 5
POST http://localhost:5050/disciplina/create
Content-Type: application/json

{
    "nome": "Disciplina 5",
    "codigo": "DISC5",
    "periodo": 5,
    "descricao": "Descrição 5"
}

### Cria disciplina 7
POST http://localhost:5050/disciplina/create
Content-Type: application/json

{
    "nome": "Disciplina 7",
    "codigo": "DISC7",
    "periodo": 7,
    "descricao": "Descrição 7"
}

### Atualiza disciplina 1
PUT http://localhost:5050/disciplina/update/2
Content-Type: application/json

{
    "nome": "Disciplina 2",
    "codigo": "DISC2",
    "periodo": 1,
    "descricao": "Descrição 2"
}

### Inativa disciplina 2
PUT http://localhost:5050/disciplina/disable/2

### Ativa disciplina 2
PUT http://localhost:5050/disciplina/activate/2
