### Retorna todas as salas
GET http://localhost:5050/sala

### Retorna somente ativas
GET http://localhost:5050/sala/actives

### Retorna sala por id
GET http://localhost:5050/sala/1

### Cria sala 1
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 1",
    "local": "Bloco 1",
    "capacidade": 1
}

### Cria sala 2
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 2",
    "local": "Bloco 2",
    "capacidade": 2
}

### Cria sala 3
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 3",
    "local": "Bloco 3",
    "capacidade": 3
}

### Cria sala 4
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 4",
    "local": "Bloco 4",
    "capacidade": 4
}

### Cria sala 5
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 5",
    "local": "Bloco 5",
    "capacidade": 5
}

### Cria sala 6
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 6",
    "local": "Bloco 6",
    "capacidade": 6
}

### Cria sala 7
POST http://localhost:5050/sala/create
Content-Type: application/json

{
    "nome": "Sala 7",
    "local": "Bloco 7",
    "capacidade": 7
}

### Atualiza sala 1
PUT http://localhost:5050/sala/update/1
Content-Type: application/json

{
    "nome": "Sala 1 Atualizada",
    "capacidade": 30
}

### Inativa sala 2
PUT http://localhost:5050/sala/disable/2

### Ativa sala 2
PUT http://localhost:5050/sala/activate/2
